version: "3.5"

services:

  db:
    container_name: db_postgres_container
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: tilt
      POSTGRES_PASSWORD: tilt_pass
      POSTGRES_DB: tilt_db
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    volumes:
     # - ./data/db:/var/lib/postgresql/data
      - ./bd/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  
  main:
   container_name: go_server
   build: './API'
   ports:
     - "8080:8080"
   depends_on:
     - db
   restart: always

  