INSERT INTO courses(link, name,type,duration) VALUES
    ('https://gb.ru/s/ai-integration-specialist','Специалист по внедрению Искусственного Интеллекта','Профильный курс','6 месяцев'),
    ('https://gb.ru/geek_university/developer','Разработчик: старт в ИТ с нуля до Junior','Программа: разработчик','12 месяцев'),
    ('https://gb.ru/geek_university/developer/programmer/python-gb','Python-разработчик: быстрый старт в профессии','Базовый курс','9 месяцев'),
    ('https://gb.ru/geek_university/developer/programmer','Программист с нуля до Junior','Базовый курс','12 месяцев'),
    ('https://gb.ru/geek_university/developer/programmer/java-gb','Java-разработчик: быстрый старт в профессии','Базовый курс','9 месяцев'),
    ('https://gb.ru/geek_university/developer/programmer/ai-spec','Разработчик искусственного интеллекта','Базовый курс','12 месяцев'),
    ('https://gb.ru/geek_university/developer/programmer/csharp','Разработчик на C#: быстрый старт в профессии','Базовый курс','9 месяцев'),
    ('https://gb.ru/geek_university/developer/programmer/frontend-gb','Frontend-разработчик: быстрый старт в профессии','Базовый курс','9 месяцев'),
    ('https://gb.ru/geek_university/developer/programmer/1c-spec-gb','Курс «1C-разработчик: быстрый старт в профессии»','Базовый курс','9 месяцев'),
    ('https://gb.ru/geek_university/developer/analyst/data-science-medicine-spec','Data Scientist в медицине: с нуля до Junior','Профильный курс','12 месяцев'),
    ('https://gb.ru/geek_university/developer/architecture/devops-spec-gb','DevOps-инженер: быстрый старт в профессии','Базовый курс','9 месяцев'),
    ('https://gb.ru/geek_university/developer/programmer/python/master','Python-разработчик с нуля до Middle','Расширенная версия','24 месяцев'),
    ('https://gb.ru/geek_university/developer/programmer/internet-of-things','Разработчик умных устройств','Базовый курс','9 месяцев'),
    ('https://gb.ru/geek_university/developer/programmer/cpp-spec-gb','Разработчик на C++: быстрый старт в профессии','Базовый курс','9 месяцев'),
    ('https://gb.ru/geek_university/developer/programmer/web','Веб-разработчик: быстрый старт в профессии','Базовый курс','9 месяцев'),
    ('https://gb.ru/geek_university/developer/architecture/devops','DevOps-инженер с нуля до Middle','Расширенная версия','24 месяцев'),
    ('https://gb.ru/geek_university/developer/qa-engineer/master','Тестировщик с нуля до Middle','Расширенная версия','24 месяцев'),
    ('https://gb.ru/geek_university/developer/programmer/cpp','Курс «Разработчик на C++ с нуля до Junior»','Расширенная версия','12 месяцев'),
    ('https://gb.ru/geek_university/developer/programmer/1c-developer','1С-разработчик с нуля до Junior','Расширенная версия','12 месяцев'),
    ('https://gb.ru/geek_university/developer/programmer/fullstack','Fullstack-разработчик: быстрый старт в профессии','Базовый курс','12 месяцев'),
    ('https://gb.ru/geek_university/developer/programmer/backend','Backend-разработчик','Базовый курс','9 месяцев'),
    ('https://gb.ru/geek_university/developer/programmer/ios','iOS-разработчик','Базовый курс','9 месяцев'),
    ('https://gb.ru/geek_university/developer/programmer/java/master','Java-разработчик с нуля до Middle','Расширенная версия','24 месяцев'),
    ('https://gb.ru/geek_university/developer/programmer/frontend/master','Frontend-разработчик с нуля до Middle','Расширенная версия','24 месяцев'),
    ('https://gb.ru/geek_university/engineer/datascience','ИТ-специалист в сфере Data Science','Профильный курс','24 месяцев'),
    ('https://gb.ru/geek_university/developer/programmer/android-spec','Android-разработчик: быстрый старт в профессии','Базовый курс','9 месяцев'),
    ('https://gb.ru/geek_university/developer/programmer/android','Android-разработчик с нуля до Junior','Расширенная версия','12 месяцев'),
    ('https://gb.ru/geek_university/developer/architecture/network-engineer','Сетевой инженер','Базовый курс','12 месяцев');